kind: ExecutorPlugin
apiVersion: argoproj.io/v1alpha1
metadata:
  name: github
spec:
  sidecar:
    container:
      image: crenshaw-dev/github-executor-plugin:latest
      imagePullPolicy: Never
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
      name: github
      ports:
        - containerPort: 4355
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
