name: Build image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

permissions:
  contents: read

jobs:
  publish:
    if: github.repository == 'crenshaw-dev/github-executor-plugin'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: crenshawdotdev
          password: ${{ secrets.DOCKERHUB_PASSWORD || inputs.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: crenshawdotdev/github-executor-plugin:${{ inputs.tag || 'latest' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
